version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    environment:
      - CONSUL_HOST=service-discovery
      - CONSUL_PORT=8500
    networks:
      - microservices-network

  # Service Discovery (Consul)
  service-discovery:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      - microservices-network

  # Message Broker (RabbitMQ)
  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - microservices-network

  # Database (PostgreSQL)
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=microservices
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Monitoring (Prometheus + Grafana)
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - microservices-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - microservices-network

  # Logging (ELK Stack)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - microservices-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    volumes:
      - ./logging/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - microservices-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - microservices-network

  # Sample Microservices
  user-service:
    build: ./services/user-service
    depends_on:
      - database
      - message-broker
      - service-discovery
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_HOST=message-broker
      - CONSUL_HOST=service-discovery
    networks:
      - microservices-network

  product-service:
    build: ./services/product-service
    depends_on:
      - database
      - message-broker
      - service-discovery
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - RABBITMQ_HOST=message-broker
      - CONSUL_HOST=service-discovery
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data:
  elasticsearch-data: 